INSERT INTO players (name) VALUES ('Даниил Медведев');
INSERT INTO players (name) VALUES ('Карен Хачанов');
INSERT INTO players (name) VALUES ('Андрей Рублёв');
INSERT INTO players (name) VALUES ('Елена Веснина');
INSERT INTO players (name) VALUES ('Анна Курникова');
INSERT INTO players (name) VALUES ('Светлана Кузнецова');
INSERT INTO players (name) VALUES ('Дмитрий Турсунов');
INSERT INTO players (name) VALUES ('Никита Кленин');
INSERT INTO players (name) VALUES ('Михаил Южный');
INSERT INTO players (name) VALUES ('Татьяна Головинова');
INSERT INTO players (name) VALUES ('Василий Иванов');
INSERT INTO players (name) VALUES ('Иван Петров');
INSERT INTO players (name) VALUES ('Сергей Смирнов');

INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 6, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 10, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 4, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 8, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 2, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 5, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 6, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 9, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 10, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 1, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 1, 1);